baseURL = "http://example.org/"
languageCode = "en-us"
defaultContentLanguage = "en-us"
title = "hugo statusline theme"
theme = "statusline"

[taxonomies]
	category = "categories"
	series = "series"
	tag = "tags"

