baseURL = "http://example.org/"
languageCode = "en-us"
title = "hugo-statusline-theme"
theme = "statusline"

[taxonomies]
	category = "categories"
	series = "series"
	tag = "tags"

[params]
	logoText = "statusline"
	logoHomeLink = "/"
	logoColor = "red"
	author = "amy dang"
	enableGoToTop = true
	[params.profile]
		name = "kirontoo"
		location = "los angeles, CA"
		email = "example@email.com"
		[params.profile.links]
			[params.profile.links.facebook]
				link = "https://example.com"
				color = "blue"
			[params.profile.links.twitter]
				link = "https://example.com"
				color = "purple"
			[params.profile.links.linkedin]
				link = "https://example.com"
				color = "yellow"
			[params.profile.links.github]
				link = "https://example.com"
				color = "red"

[languages]
	[languages.en]
		title = "statusline"
		[languages.en.menu]
			[[languages.en.menu.main]]
				identifier = "about"
				name = "about"
				url = "/about"
				pre = "purple"
			[[languages.en.menu.main]]
				identifier = "projects"
				name = "projects"
				url = "/projects"
				pre = "cyan"
			[[languages.en.menu.main]]
				identifier = "blog"
				name = "blog"
				url = "/blog"
				pre = "yellow"



