baseURL = "http://example.org/"
languageCode = "en-us"
title = "hugo-statusline-theme"
theme = "statusline"

[taxonomies]
	category = "categories"
	series = "series"
	tag = "tags"

[markup]
	[markup.tableOfContents]
		endLevel = 6
		ordered = false
		startLevel = 1
	[markup.goldmark]
		[markup.goldmark.extensions]
			definitionList = true
			footnote = true
			linkify = true
			strikethrough = true
			table = true
			taskList = true
			typographer = true
		[markup.goldmark.parser]
			attribute = true
			autoHeadingID = true
			autoHeadingIDType = "github"
		[markup.goldmark.renderer]
			hardWraps = false
			unsafe = true
			xhtml = false

[params]
	logoText = "statusline"
	logoHomeLink = "/"
	logoColor = "red"
	author = "amy dang"
	enableGoToTop = true
	enableParagraphIndent = false
	enableTOC = true
	enableLastModified = false
	enableSidebar = true
	listDateFormat = "01-02"
	singleDateFormat = "Jan 02, 2006"
	[params.profile]
		name = "kirontoo"
		location = "los angeles, CA"
		email = "example@email.com"
		bio = "A short bio you can write. It will be limited to 200 characters to prevent long paragraphs."
		[params.profile.links]
			[params.profile.links.facebook]
				link = "https://example.com"
				color = "blue"
			[params.profile.links.twitter]
				link = "https://example.com"
				color = "purple"
			[params.profile.links.linkedin]
				link = "https://example.com"
				color = "yellow"
			[params.profile.links.github]
				link = "https://example.com"
				color = "red"
	[params.projects]
		enableSidebar = true
	[params.archive]
		pageTypeBlacklist = [ "archive", "projects", "about" ]
		groupByDateFormat = "2006-01"
		publishDateFormat = "Jan 02"
		enableSidebar = true
		[params.archive.color]
			type = "blue"
			groupDate = "pink"
			publishDate = "yellow"
	[params.pagination]
		enable = true
		pageColor = "blue"
		activePageColor = "purple"
		itemsPerPage = 4

[languages]
	[languages.en]
		title = "statusline"
		[languages.en.menu]
			[[languages.en.menu.main]]
				identifier = "about"
				name = "about"
				url = "/about"
				pre = "purple"
				weight = 1
			[[languages.en.menu.main]]
				identifier = "projects"
				name = "projects"
				url = "/projects"
				pre = "cyan"
				weight = 2
			[[languages.en.menu.main]]
				identifier = "blog"
				name = "blog"
				url = "/blog"
				pre = "yellow"
				weight = 3
			[[languages.en.menu.main]]
				identifier = "archive"
				name = "archive"
				url = "/archive"
				weight = 4



