[build]
  publish = "exampleSite/public"
  command = "cd exampleSite && hugo"

[context.production]
  [context.production.environment]
    HUGO_VERSION = "0.71.0"
    HUGO_BASEURL = "https://hugo-statuslinet-theme.netlify.com/"

# PR previews
[context.deploy-preview]
  command = "cd exampleSite && hugo -b ${DEPLOY_PRIME_URL}"
  [context.deploy-preview.environment]
    HUGO_VERSION = "0.71.0"
