baseURL = "http://localhost:1313"
languageCode = "en-us"
defaultContentLanguage ="en"
title = "hugo-statusline-theme"
paginate = 6
theme="statusline"

[taxonomies]
	category = "categories"
	series = "series"
	tag = "tags"

[markup]
	[markup.highlight]
		codeFences = true
		guessSyntax = false
		hl_Lines = ""
		lineNoStart = 1
		lineNos = true
		lineNumbersInTable = false
		noClasses = true
		style = "dracula"
		tabWidth = 2

	[markup.tableOfContents]
		endLevel = 6
		ordered = false
		startLevel = 2

	[markup.goldmark]
		[markup.goldmark.extensions]
			definitionList = true
			footnote = true
			linkify = true
			strikethrough = true
			table = true
			taskList = true
			typographer = true

		[markup.goldmark.parser]
			attribute = true
			autoHeadingID = true
			autoHeadingIDType = "github"

		[markup.goldmark.renderer]
			hardWraps = false
			unsafe = true
			xhtml = false

[params]
	# colorscheme="gruvbox-dark"
	# colorscheme="gruvbox-light"
	colorscheme="deepspace"
	titleColor = "cyan"
	author = "kirontoo"
	enableGoToTop = true
	enableParagraphIndent = false
	enableTOC = true
	enableLastModified = true
	enableSidebar = true
	listDateFormat = "01-02-2006"
	singleDateFormat = "Jan 02, 2006"
	mainSections = [ "blog", "org", "cpp" ]

	[params.profile]
		name = "kirontoo"
		location = "los angeles, CA"
		email = "example@email.com"
		website = "https://github.com/kirontoo/hugo-statusline-theme"
		bio = "A short bio you can write. It will be limited to 200 characters to prevent long paragraphs."
		occupation = "Web Developer"

		[params.profile.image]
			# to link your own image, place them in the static/image folder:
			# link = "images/your-image.png"
			link = "https://loremflickr.com/320/240"
			alt = "placeholder cat image"
			# title = "placeholder cat image"

		[params.profile.links]
			[params.profile.links.instagram]
				link = "https://example.com"
				color = "white"

			[params.profile.links.facebook]
				link = "https://example.com"
				color = "blue"

			[params.profile.links.twitter]
				link = "https://example.com"
				color = "cyan"

			[params.profile.links.linkedin]
				link = "https://example.com"
				color = "yellow"

			[params.profile.links.github]
				link = "https://example.com"
				color = "red"

	[params.projects]
		enableSidebar = true
		borderStyle = "box" # Round or box
		listStyle = "grid"

	[params.archive]
		pageTypeBlacklist = [ "archive", "projects", "about" ]
		publishDateFormat = "Jan 02"
		enableSidebar = true

		[params.archive.color]
			type = "blue"
			groupDate = "pink"
			publishDate = "yellow"

	[params.pagination]
		enable = true
		pageColor = "cyan"
		activePageColor = "pink"

[menu]
	[[menu.main]]
		identifier = "about"
		name = "about"
		url = "/about"
		pre = "purple"
		weight = 1

	[[menu.main]]
		identifier = "projects"
		name = "projects"
		url = "/projects"
		pre = "cyan"
		weight = 2

	[[menu.main]]
		parent = "projects"
		name = "bots"
		url = "/projects/web-app"
		pre = "cyan"

	[[menu.main]]
		identifier = "blog"
		name = "blog"
		url = "/blog"
		pre = "yellow"
		weight = 3

	[[menu.main]]
		identifier = "archive"
		name = "archive"
		url = "/archive"
		weight = 6

[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    anonymizeIP = false
    disable = false
    respectDoNotTrack = false
    useSessionStorage = false
  [privacy.instagram]
    disable = false
    simple = false
  [privacy.twitter]
    disable = false
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = false
    enableDNT = false
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = false
