baseURL = "http://localhost:1313"
languageCode = "en-us"
defaultContentLanguage ="en"
title = "hugo-statusline-theme"
paginate = 10
theme="statusline"

[taxonomies]
	category = "categories"
	series = "series"
	tag = "tags"

[markup]
	[markup.highlight]
		codeFences = true
		guessSyntax = false
		hl_Lines = ""
		lineNoStart = 1
		lineNos = true
		lineNumbersInTable = false
		noClasses = true
		style = "dracula"
		tabWidth = 2

	[markup.tableOfContents]
		endLevel = 6
		ordered = false
		startLevel = 1

	[markup.goldmark]
		[markup.goldmark.extensions]
			definitionList = true
			footnote = true
			linkify = true
			strikethrough = true
			table = true
			taskList = true
			typographer = true

		[markup.goldmark.parser]
			attribute = true
			autoHeadingID = true
			autoHeadingIDType = "github"

		[markup.goldmark.renderer]
			hardWraps = false
			unsafe = true
			xhtml = false

[params]
	logoText = "statusline"
	logoHomeLink = "/"
	logoColor = "red"
	author = "amy dang"
	enableGoToTop = true
	enableParagraphIndent = false
	enableTOC = true
	enableLastModified = true
	enableSidebar = true
	listDateFormat = "01-02-2006"
	singleDateFormat = "Jan 02, 2006"
	mainSections = [ "blog", "org", "cpp" ]

	[params.profile]
		name = "kirontoo"
		location = "los angeles, CA"
		email = "example@email.com"
		bio = "A short bio you can write. It will be limited to 200 characters to prevent long paragraphs."
		occupation = "Web Developer"

		[params.profile.image]
			link = "images/starship.png"
			alt = "starship"
			title = "starship"

		[params.profile.links]
			[params.profile.links.facebook]
				link = "https://example.com"
				color = "blue"

			[params.profile.links.twitter]
				link = "https://example.com"
				color = "purple"

			[params.profile.links.linkedin]
				link = "https://example.com"
				color = "yellow"

			[params.profile.links.github]
				link = "https://example.com"
				color = "red"

	[params.projects]
		enableSidebar = true
		borderStyle = "box"
		listStyle = "grid"

	[params.archive]
		pageTypeBlacklist = [ "archive", "projects", "about" ]
		publishDateFormat = "Jan 02"
		enableSidebar = true

		[params.archive.color]
			type = "blue"
			groupDate = "pink"
			publishDate = "yellow"

	[params.pagination]
		enable = true
		pageColor = "cyan"
		activePageColor = "pink"

[languages]
	[languages.en]
		title = "statusline"
		[languages.en.menu]
			[[languages.en.menu.main]]
				identifier = "about"
				name = "about"
				url = "/about"
				pre = "purple"
				weight = 1

			[[languages.en.menu.main]]
				identifier = "projects"
				name = "projects"
				url = "/projects"
				pre = "cyan"
				weight = 2

			[[languages.en.menu.main]]
				parent = "projects"
				name = "python"
				url = "/projects/python"
				pre = "cyan"

			[[languages.en.menu.main]]
				parent = "projects"
				name = "bots"
				url = "/projects/bots"
				pre = "cyan"

			[[languages.en.menu.main]]
				identifier = "blog"
				name = "blog"
				url = "/blog"
				pre = "yellow"
				weight = 3

			[[languages.en.menu.main]]
				identifier = "archive"
				name = "archive"
				url = "/archive"
				weight = 6

			[[languages.en.menu.main]]
				identifier = "org"
				name = "org"
				url = "/org"
				pre = "orange"
				weight = 3

			[[languages.en.menu.main]]
				identifier = "cpp"
				name = "cpp"
				url = "/cpp"
				pre = "blue"
				weight = 4

